import { Event, TicketPackage, Order } from "@/types";

// ─── Mock Events ─────────────────────────────────────────────────────────────

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Lagos Jazz & Wine Festival",
    description:
      "A sophisticated evening of live jazz performances paired with premium wines from around the world. Set in the heart of Lagos, this event brings together the finest musicians and sommeliers for an unforgettable cultural experience. Dress code: Smart Casual.",
    location: "Lagos, Nigeria",
    venue: "Eko Hotels & Suites, Victoria Island",
    date: "2026-04-18T18:00:00",
    end_date: "2026-04-18T23:00:00",
    category: "Music",
    image_url:
      "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800&q=80",
    organizer: "Oryx Events",
    is_featured: true,
    is_published: true,
    created_at: "2026-01-01T00:00:00",
    updated_at: "2026-01-01T00:00:00",
  },
  {
    id: "2",
    title: "AfroBeats Night: Volume 12",
    description:
      "The biggest Afrobeats concert of the year is back. Featuring top-charting artists, dazzling stage production, and an electric atmosphere that will leave you speechless. Book your spot before they sell out.",
    location: "Abuja, Nigeria",
    venue: "International Conference Centre, Abuja",
    date: "2026-05-02T20:00:00",
    end_date: "2026-05-03T02:00:00",
    category: "Music",
    image_url:
      "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80",
    organizer: "Groove Nation",
    is_featured: true,
    is_published: true,
    created_at: "2026-01-10T00:00:00",
    updated_at: "2026-01-10T00:00:00",
  },
  {
    id: "3",
    title: "Lagos Tech Summit 2026",
    description:
      "Nigeria's premier technology conference, connecting founders, investors, and innovators. Three days of keynotes, workshops, and networking sessions across the full spectrum of African tech.",
    location: "Lagos, Nigeria",
    venue: "Landmark Event Centre, Victoria Island",
    date: "2026-06-10T09:00:00",
    end_date: "2026-06-12T17:00:00",
    category: "Technology",
    image_url:
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    organizer: "TechBridge Africa",
    is_featured: false,
    is_published: true,
    created_at: "2026-01-15T00:00:00",
    updated_at: "2026-01-15T00:00:00",
  },
  {
    id: "4",
    title: "Naija Food Festival",
    description:
      "Celebrate the rich and diverse flavors of Nigerian cuisine. Sample dishes from across the country's six geopolitical zones, watch live cooking demonstrations, and meet celebrity chefs.",
    location: "Port Harcourt, Nigeria",
    venue: "Port Harcourt Civic Centre",
    date: "2026-04-25T11:00:00",
    end_date: "2026-04-26T20:00:00",
    category: "Food & Drink",
    image_url:
      "https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800&q=80",
    organizer: "Flavours of Naija",
    is_featured: true,
    is_published: true,
    created_at: "2026-01-20T00:00:00",
    updated_at: "2026-01-20T00:00:00",
  },
  {
    id: "5",
    title: "The Art of Now: Contemporary Exhibition",
    description:
      "An immersive art exhibition showcasing works from 30 of Africa's most exciting contemporary artists. Featuring painting, sculpture, photography, and digital art in a specially designed gallery space.",
    location: "Lagos, Nigeria",
    venue: "Terra Kulture Arena, Victoria Island",
    date: "2026-05-15T10:00:00",
    end_date: "2026-05-20T19:00:00",
    category: "Arts",
    image_url:
      "https://images.unsplash.com/photo-1531058020387-3be344556be6?w=800&q=80",
    organizer: "Oryx Events",
    is_featured: false,
    is_published: true,
    created_at: "2026-02-01T00:00:00",
    updated_at: "2026-02-01T00:00:00",
  },
  {
    id: "6",
    title: "The Business of Fashion Forum",
    description:
      "A premium two-day forum for fashion entrepreneurs, designers, and creatives. Panels on scaling African fashion brands globally, sustainable fashion practices, and securing investment.",
    location: "Lagos, Nigeria",
    venue: "Four Points by Sheraton, Oniru",
    date: "2026-07-07T09:00:00",
    end_date: "2026-07-08T18:00:00",
    category: "Fashion",
    image_url:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    organizer: "Style Capital Africa",
    is_featured: false,
    is_published: true,
    created_at: "2026-02-10T00:00:00",
    updated_at: "2026-02-10T00:00:00",
  },
];

// ─── Mock Packages ─────────────────────────────────────────────────────────────

export const mockPackages: Record<string, TicketPackage[]> = {
  "1": [
    {
      id: "pkg-1-regular",
      event_id: "1",
      name: "Regular",
      tier: "Regular",
      price: 15000,
      perks: ["General admission", "Welcome drink", "Live jazz access"],
      total_slots: 500,
      available_slots: 234,
      is_available: true,
      created_at: "2026-01-01T00:00:00",
    },
    {
      id: "pkg-1-vip",
      event_id: "1",
      name: "VIP",
      tier: "VIP",
      price: 45000,
      perks: [
        "Priority seating",
        "3-course dinner",
        "Wine pairing",
        "Meet & greet with performers",
        "Exclusive lounge access",
      ],
      total_slots: 100,
      available_slots: 22,
      is_available: true,
      created_at: "2026-01-01T00:00:00",
    },
    {
      id: "pkg-1-table",
      event_id: "1",
      name: "Table for 10",
      tier: "Table",
      price: 350000,
      perks: [
        "Reserved table (10 seats)",
        "Dedicated waiter",
        "Premium wine selection",
        "Personalized menu",
        "VIP arrival experience",
        "Photo session",
      ],
      total_slots: 20,
      available_slots: 5,
      is_available: true,
      created_at: "2026-01-01T00:00:00",
    },
  ],
  "2": [
    {
      id: "pkg-2-regular",
      event_id: "2",
      name: "Regular",
      tier: "Regular",
      price: 10000,
      perks: ["General admission", "Access to main stage"],
      total_slots: 2000,
      available_slots: 856,
      is_available: true,
      created_at: "2026-01-10T00:00:00",
    },
    {
      id: "pkg-2-vip",
      event_id: "2",
      name: "VIP",
      tier: "VIP",
      price: 35000,
      perks: [
        "VIP floor access",
        "Premium bar",
        "Artist meet & greet",
        "Exclusive after-party",
      ],
      total_slots: 300,
      available_slots: 48,
      is_available: true,
      created_at: "2026-01-10T00:00:00",
    },
    {
      id: "pkg-2-table",
      event_id: "2",
      name: "VIP Table",
      tier: "Table",
      price: 250000,
      perks: [
        "Table for 8",
        "Bottle service",
        "Dedicated host",
        "After-party access",
      ],
      total_slots: 30,
      available_slots: 7,
      is_available: true,
      created_at: "2026-01-10T00:00:00",
    },
  ],
  "3": [
    {
      id: "pkg-3-regular",
      event_id: "3",
      name: "Delegate",
      tier: "Regular",
      price: 25000,
      perks: ["All sessions", "Lunch", "Networking events", "Certificate"],
      total_slots: 800,
      available_slots: 312,
      is_available: true,
      created_at: "2026-01-15T00:00:00",
    },
    {
      id: "pkg-3-vip",
      event_id: "3",
      name: "Speaker / VIP",
      tier: "VIP",
      price: 75000,
      perks: [
        "All sessions + speaker access",
        "VIP networking dinner",
        "Workshop priority",
        "Investor matchmaking",
      ],
      total_slots: 50,
      available_slots: 11,
      is_available: true,
      created_at: "2026-01-15T00:00:00",
    },
  ],
  "4": [
    {
      id: "pkg-4-regular",
      event_id: "4",
      name: "Day Pass",
      tier: "Regular",
      price: 5000,
      perks: ["One-day access", "Festival map & guide"],
      total_slots: 1000,
      available_slots: 650,
      is_available: true,
      created_at: "2026-01-20T00:00:00",
    },
    {
      id: "pkg-4-vip",
      event_id: "4",
      name: "Weekend VIP",
      tier: "VIP",
      price: 20000,
      perks: [
        "2-day access",
        "Tasting tokens (x20)",
        "Chef demos front row",
        "VIP lounge",
      ],
      total_slots: 150,
      available_slots: 43,
      is_available: true,
      created_at: "2026-01-20T00:00:00",
    },
  ],
  "5": [
    {
      id: "pkg-5-regular",
      event_id: "5",
      name: "General Entry",
      tier: "Regular",
      price: 3000,
      perks: ["Exhibition access", "Art catalog"],
      total_slots: 2000,
      available_slots: 1200,
      is_available: true,
      created_at: "2026-02-01T00:00:00",
    },
    {
      id: "pkg-5-vip",
      event_id: "5",
      name: "Collector's Pass",
      tier: "VIP",
      price: 18000,
      perks: [
        "Opening night gala",
        "Artist Q&A sessions",
        "Guided curator tour",
        "10% off artworks",
      ],
      total_slots: 80,
      available_slots: 15,
      is_available: true,
      created_at: "2026-02-01T00:00:00",
    },
  ],
  "6": [
    {
      id: "pkg-6-regular",
      event_id: "6",
      name: "Delegate",
      tier: "Regular",
      price: 30000,
      perks: ["Both days access", "Lunch & refreshments", "Materials kit"],
      total_slots: 300,
      available_slots: 189,
      is_available: true,
      created_at: "2026-02-10T00:00:00",
    },
    {
      id: "pkg-6-vip",
      event_id: "6",
      name: "VIP Delegate",
      tier: "VIP",
      price: 80000,
      perks: [
        "Priority seating",
        "Panel speaker access",
        "1:1 mentorship session",
        "Exclusive gala dinner",
      ],
      total_slots: 40,
      available_slots: 8,
      is_available: true,
      created_at: "2026-02-10T00:00:00",
    },
  ],
};

export const mockOrders: Order[] = [];
