import { Event, TicketPackage, Order, Hotel, RoomType, HotelBooking } from "@/types";

// ─── Mock Events ─────────────────────────────────────────────────────────────

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Doha Jazz & Fine Dining Gala",
    description:
      "A sophisticated evening of live jazz performances paired with premium international wines and a curated fine-dining experience. Set against the stunning Doha skyline, this event brings together the finest musicians and sommeliers for an unforgettable cultural evening. Dress code: Black Tie.",
    location: "Doha, Qatar",
    venue: "Waldorf Astoria Doha West Bay",
    date: "2026-04-18T18:00:00",
    end_date: "2026-04-18T23:00:00",
    category: "Music",
    image_url:
      "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800&q=80",
    organizer: "Oryx Events",
    is_featured: true,
    is_published: true,
    created_at: "2026-01-01T00:00:00",
    updated_at: "2026-01-01T00:00:00",
  },
  {
    id: "2",
    title: "Arabian Nights Music Festival",
    description:
      "Qatar's biggest music celebration is back. Featuring acclaimed regional and international artists, breathtaking stage production, and an electric atmosphere under the stars of the Arabian Gulf. Book your spot before they sell out.",
    location: "Lusail, Qatar",
    venue: "Lusail Stadium Grounds",
    date: "2026-05-02T20:00:00",
    end_date: "2026-05-03T02:00:00",
    category: "Music",
    image_url:
      "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80",
    organizer: "Gulf Live Entertainment",
    is_featured: true,
    is_published: true,
    created_at: "2026-01-10T00:00:00",
    updated_at: "2026-01-10T00:00:00",
  },
  {
    id: "3",
    title: "Qatar Tech & Innovation Summit 2026",
    description:
      "Qatar's premier technology conference, connecting founders, investors, and innovators shaping the future of the Gulf region. Three days of keynotes, workshops, and networking sessions across fintech, AI, and smart city solutions.",
    location: "Doha, Qatar",
    venue: "Qatar National Convention Centre",
    date: "2026-06-10T09:00:00",
    end_date: "2026-06-12T17:00:00",
    category: "Technology",
    image_url:
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    organizer: "Qatar Tech Hub",
    is_featured: false,
    is_published: true,
    created_at: "2026-01-15T00:00:00",
    updated_at: "2026-01-15T00:00:00",
  },
  {
    id: "4",
    title: "Doha International Food Festival",
    description:
      "Celebrate Qatar's vibrant culinary scene. Sample world-class dishes from over 30 countries, watch live cooking demonstrations by celebrity chefs, and explore the rich flavours of Qatari heritage cuisine.",
    location: "Doha, Qatar",
    venue: "Katara Cultural Village, Doha",
    date: "2026-04-25T11:00:00",
    end_date: "2026-04-26T20:00:00",
    category: "Food & Drink",
    image_url:
      "https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800&q=80",
    organizer: "Katara Events",
    is_featured: true,
    is_published: true,
    created_at: "2026-01-20T00:00:00",
    updated_at: "2026-01-20T00:00:00",
  },
  {
    id: "5",
    title: "Gulf Contemporary Art Exhibition",
    description:
      "An immersive art exhibition showcasing works from 30 of the Gulf's most exciting contemporary artists. Featuring painting, sculpture, photography, and digital installations in a specially designed gallery space at the Museum of Islamic Art.",
    location: "Doha, Qatar",
    venue: "Museum of Islamic Art, Doha",
    date: "2026-05-15T10:00:00",
    end_date: "2026-05-20T19:00:00",
    category: "Arts",
    image_url:
      "https://images.unsplash.com/photo-1531058020387-3be344556be6?w=800&q=80",
    organizer: "Oryx Events",
    is_featured: false,
    is_published: true,
    created_at: "2026-02-01T00:00:00",
    updated_at: "2026-02-01T00:00:00",
  },
  {
    id: "6",
    title: "Qatar Fashion & Luxury Forum",
    description:
      "A premium two-day forum for fashion entrepreneurs, designers, and luxury brand leaders. Panels on expanding Gulf fashion brands globally, sustainable luxury, and the future of retail in the MENA region.",
    location: "Doha, Qatar",
    venue: "St. Regis Doha, West Bay",
    date: "2026-07-07T09:00:00",
    end_date: "2026-07-08T18:00:00",
    category: "Fashion",
    image_url:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    organizer: "Gulf Style Collective",
    is_featured: false,
    is_published: true,
    created_at: "2026-02-10T00:00:00",
    updated_at: "2026-02-10T00:00:00",
  },
];

// ─── Mock Packages ─────────────────────────────────────────────────────────────

export const mockPackages: Record<string, TicketPackage[]> = {
  "1": [
    {
      id: "pkg-1-regular",
      event_id: "1",
      name: "Regular",
      tier: "Regular",
      price: 450,
      perks: ["General admission", "Welcome drink", "Live jazz access"],
      total_slots: 500,
      available_slots: 234,
      is_available: true,
      created_at: "2026-01-01T00:00:00",
    },
    {
      id: "pkg-1-vip",
      event_id: "1",
      name: "VIP",
      tier: "VIP",
      price: 1200,
      perks: [
        "Priority seating",
        "5-course dinner",
        "Wine pairing",
        "Meet & greet with performers",
        "Exclusive lounge access",
      ],
      total_slots: 100,
      available_slots: 22,
      is_available: true,
      created_at: "2026-01-01T00:00:00",
    },
    {
      id: "pkg-1-table",
      event_id: "1",
      name: "Table for 10",
      tier: "Table",
      price: 9500,
      perks: [
        "Reserved table (10 seats)",
        "Dedicated butler service",
        "Premium wine selection",
        "Personalised menu",
        "VIP arrival experience",
        "Photo session",
      ],
      total_slots: 20,
      available_slots: 5,
      is_available: true,
      created_at: "2026-01-01T00:00:00",
    },
  ],
  "2": [
    {
      id: "pkg-2-regular",
      event_id: "2",
      name: "Regular",
      tier: "Regular",
      price: 300,
      perks: ["General admission", "Access to main stage"],
      total_slots: 2000,
      available_slots: 856,
      is_available: true,
      created_at: "2026-01-10T00:00:00",
    },
    {
      id: "pkg-2-vip",
      event_id: "2",
      name: "VIP",
      tier: "VIP",
      price: 950,
      perks: [
        "VIP floor access",
        "Premium bar",
        "Artist meet & greet",
        "Exclusive after-party",
      ],
      total_slots: 300,
      available_slots: 48,
      is_available: true,
      created_at: "2026-01-10T00:00:00",
    },
    {
      id: "pkg-2-table",
      event_id: "2",
      name: "VIP Table",
      tier: "Table",
      price: 7000,
      perks: [
        "Table for 8",
        "Bottle service",
        "Dedicated host",
        "After-party access",
      ],
      total_slots: 30,
      available_slots: 7,
      is_available: true,
      created_at: "2026-01-10T00:00:00",
    },
  ],
  "3": [
    {
      id: "pkg-3-regular",
      event_id: "3",
      name: "Delegate",
      tier: "Regular",
      price: 750,
      perks: ["All sessions", "Lunch", "Networking events", "Certificate"],
      total_slots: 800,
      available_slots: 312,
      is_available: true,
      created_at: "2026-01-15T00:00:00",
    },
    {
      id: "pkg-3-vip",
      event_id: "3",
      name: "Speaker / VIP",
      tier: "VIP",
      price: 2200,
      perks: [
        "All sessions + speaker access",
        "VIP networking dinner",
        "Workshop priority",
        "Investor matchmaking",
      ],
      total_slots: 50,
      available_slots: 11,
      is_available: true,
      created_at: "2026-01-15T00:00:00",
    },
  ],
  "4": [
    {
      id: "pkg-4-regular",
      event_id: "4",
      name: "Day Pass",
      tier: "Regular",
      price: 150,
      perks: ["One-day access", "Festival map & guide"],
      total_slots: 1000,
      available_slots: 650,
      is_available: true,
      created_at: "2026-01-20T00:00:00",
    },
    {
      id: "pkg-4-vip",
      event_id: "4",
      name: "Weekend VIP",
      tier: "VIP",
      price: 600,
      perks: [
        "2-day access",
        "Tasting tokens (x20)",
        "Chef demos front row",
        "VIP lounge",
      ],
      total_slots: 150,
      available_slots: 43,
      is_available: true,
      created_at: "2026-01-20T00:00:00",
    },
  ],
  "5": [
    {
      id: "pkg-5-regular",
      event_id: "5",
      name: "General Entry",
      tier: "Regular",
      price: 100,
      perks: ["Exhibition access", "Art catalog"],
      total_slots: 2000,
      available_slots: 1200,
      is_available: true,
      created_at: "2026-02-01T00:00:00",
    },
    {
      id: "pkg-5-vip",
      event_id: "5",
      name: "Collector's Pass",
      tier: "VIP",
      price: 550,
      perks: [
        "Opening night gala",
        "Artist Q&A sessions",
        "Guided curator tour",
        "10% off artworks",
      ],
      total_slots: 80,
      available_slots: 15,
      is_available: true,
      created_at: "2026-02-01T00:00:00",
    },
  ],
  "6": [
    {
      id: "pkg-6-regular",
      event_id: "6",
      name: "Delegate",
      tier: "Regular",
      price: 900,
      perks: ["Both days access", "Lunch & refreshments", "Materials kit"],
      total_slots: 300,
      available_slots: 189,
      is_available: true,
      created_at: "2026-02-10T00:00:00",
    },
    {
      id: "pkg-6-vip",
      event_id: "6",
      name: "VIP Delegate",
      tier: "VIP",
      price: 2500,
      perks: [
        "Priority seating",
        "Panel speaker access",
        "1:1 mentorship session",
        "Exclusive gala dinner",
      ],
      total_slots: 40,
      available_slots: 8,
      is_available: true,
      created_at: "2026-02-10T00:00:00",
    },
  ],
};

export const mockOrders: Order[] = [
  {
    id: "ord-001",
    user_id: "user-1",
    package_id: "pkg-1-vip",
    event_id: "1",
    quantity: 2,
    total_price: 2436,
    status: "confirmed",
    guest_name: "Khalid Al-Mansoori",
    guest_email: "khalid@example.com",
    payment_reference: "PSK-2026-0401",
    created_at: "2026-03-15T10:30:00",
  },
  {
    id: "ord-002",
    user_id: "user-2",
    package_id: "pkg-2-regular",
    event_id: "2",
    quantity: 4,
    total_price: 1218,
    status: "confirmed",
    guest_name: "Aisha Al-Thani",
    guest_email: "aisha@example.com",
    payment_reference: "PSK-2026-0402",
    created_at: "2026-03-16T14:15:00",
  },
  {
    id: "ord-003",
    user_id: "user-3",
    package_id: "pkg-3-regular",
    event_id: "3",
    quantity: 1,
    total_price: 761,
    status: "confirmed",
    guest_name: "Omar Hassan",
    guest_email: "omar@example.com",
    payment_reference: "PSK-2026-0403",
    created_at: "2026-03-17T09:00:00",
  },
  {
    id: "ord-004",
    user_id: "user-4",
    package_id: "pkg-1-table",
    event_id: "1",
    quantity: 1,
    total_price: 9643,
    status: "confirmed",
    guest_name: "Fatima Al-Kuwari",
    guest_email: "fatima@example.com",
    payment_reference: "PSK-2026-0404",
    created_at: "2026-03-18T11:45:00",
  },
  {
    id: "ord-005",
    user_id: "user-5",
    package_id: "pkg-4-vip",
    event_id: "4",
    quantity: 2,
    total_price: 1218,
    status: "confirmed",
    guest_name: "Mohammed Al-Dosari",
    guest_email: "mohammed@example.com",
    payment_reference: "PSK-2026-0405",
    created_at: "2026-03-19T16:20:00",
  },
  {
    id: "ord-006",
    package_id: "pkg-2-vip",
    event_id: "2",
    quantity: 3,
    total_price: 2893,
    status: "confirmed",
    guest_name: "Sara Al-Emadi",
    guest_email: "sara@example.com",
    payment_reference: "PSK-2026-0406",
    created_at: "2026-03-20T13:00:00",
  },
  {
    id: "ord-007",
    user_id: "user-6",
    package_id: "pkg-5-regular",
    event_id: "5",
    quantity: 2,
    total_price: 203,
    status: "confirmed",
    guest_name: "Noor Al-Marri",
    guest_email: "noor@example.com",
    payment_reference: "PSK-2026-0407",
    created_at: "2026-03-21T10:00:00",
  },
  {
    id: "ord-008",
    user_id: "user-7",
    package_id: "pkg-6-vip",
    event_id: "6",
    quantity: 1,
    total_price: 2538,
    status: "pending",
    guest_name: "Jassim Al-Baker",
    guest_email: "jassim@example.com",
    created_at: "2026-03-22T08:30:00",
  },
];

// ─── Mock Hotels ─────────────────────────────────────────────────────────────

export const mockHotels: Hotel[] = [
  {
    id: "h1",
    name: "Waldorf Astoria Doha West Bay",
    description:
      "An icon of refined luxury on the Doha skyline. Floor-to-ceiling views of the Arabian Gulf, a destination spa, and award-winning dining make this the definitive choice for discerning travellers attending events in the capital.",
    location: "Doha, Qatar",
    city: "Doha",
    address: "West Bay, Diplomatic District, Doha, Qatar",
    image_url:
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1000&q=80",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1000&q=80",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1000&q=80",
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1000&q=80",
    ],
    star_rating: 5,
    amenities: [
      "Free Wi-Fi",
      "Infinity Pool",
      "Spa & Wellness",
      "Airport Transfer",
      "Fine Dining",
      "Fitness Centre",
      "Valet Parking",
      "Concierge",
    ],
    is_featured: true,
    is_published: true,
    created_at: "2026-01-05T00:00:00",
    updated_at: "2026-01-05T00:00:00",
  },
  {
    id: "h2",
    name: "The St. Regis Doha",
    description:
      "Set along a private beach, The St. Regis blends Arabian grandeur with signature butler service. Expansive suites, seventeen restaurants and lounges, and a serene spa create an unforgettable base for your stay.",
    location: "Doha, Qatar",
    city: "Doha",
    address: "Doha West Bay, P.O. Box 14435, Doha, Qatar",
    image_url:
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1000&q=80",
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1000&q=80",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1000&q=80",
    ],
    star_rating: 5,
    amenities: [
      "Free Wi-Fi",
      "Private Beach",
      "Butler Service",
      "Spa & Wellness",
      "Multiple Restaurants",
      "Kids Club",
      "Fitness Centre",
    ],
    is_featured: true,
    is_published: true,
    created_at: "2026-01-08T00:00:00",
    updated_at: "2026-01-08T00:00:00",
  },
  {
    id: "h3",
    name: "Mondrian Doha",
    description:
      "A bold, design-led address in the heart of Doha. Theatrical interiors, a rooftop pool, and a celebrated nightlife and dining scene make Mondrian the choice for guests who want their stay to be an event in itself.",
    location: "Doha, Qatar",
    city: "Doha",
    address: "West Bay Lagoon, Doha, Qatar",
    image_url:
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1000&q=80",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1000&q=80",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1000&q=80",
    ],
    star_rating: 5,
    amenities: [
      "Free Wi-Fi",
      "Rooftop Pool",
      "Spa & Wellness",
      "Nightclub",
      "Fine Dining",
      "Fitness Centre",
      "Valet Parking",
    ],
    is_featured: false,
    is_published: true,
    created_at: "2026-01-12T00:00:00",
    updated_at: "2026-01-12T00:00:00",
  },
  {
    id: "h4",
    name: "Lusail Marina Suites",
    description:
      "Contemporary all-suite living overlooking the Lusail Marina. Spacious residences with full kitchens, ideal for longer stays and families attending festivals and stadium events in Lusail.",
    location: "Lusail, Qatar",
    city: "Lusail",
    address: "Marina District, Lusail City, Qatar",
    image_url:
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=1000&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1000&q=80",
    ],
    star_rating: 4,
    amenities: [
      "Free Wi-Fi",
      "Outdoor Pool",
      "Kitchenette",
      "Marina Views",
      "Fitness Centre",
      "Free Parking",
    ],
    is_featured: false,
    is_published: true,
    created_at: "2026-01-18T00:00:00",
    updated_at: "2026-01-18T00:00:00",
  },
  {
    id: "h5",
    name: "The Statement Hotel Abuja",
    description:
      "Abuja's premier five-star address in the Central Business District. Elegant rooms, a rooftop lounge, and effortless access to the city's business and cultural calendar.",
    location: "Abuja, Nigeria",
    city: "Abuja",
    address:
      "1002 First Avenue, Central Business District, FCT, Abuja, Nigeria",
    image_url:
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1000&q=80",
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1000&q=80",
      "https://images.unsplash.com/photo-1590073242678-70ee3fc28e8e?w=1000&q=80",
    ],
    star_rating: 5,
    amenities: [
      "Free Wi-Fi",
      "Rooftop Lounge",
      "Spa & Wellness",
      "Airport Transfer",
      "Restaurant",
      "Fitness Centre",
      "Business Centre",
    ],
    is_featured: true,
    is_published: true,
    created_at: "2026-01-22T00:00:00",
    updated_at: "2026-01-22T00:00:00",
  },
  {
    id: "h6",
    name: "Katara Hills Boutique Resort",
    description:
      "An intimate boutique retreat moments from Katara Cultural Village. Garden villas, a quiet pool, and locally inspired cuisine for guests who prefer charm and calm over scale.",
    location: "Doha, Qatar",
    city: "Doha",
    address: "Katara Hills, Doha, Qatar",
    image_url:
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1000&q=80",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1000&q=80",
    ],
    star_rating: 4,
    amenities: [
      "Free Wi-Fi",
      "Garden Pool",
      "Restaurant",
      "Free Parking",
      "Concierge",
    ],
    is_featured: false,
    is_published: true,
    created_at: "2026-02-02T00:00:00",
    updated_at: "2026-02-02T00:00:00",
  },
];

// ─── Mock Room Types ─────────────────────────────────────────────────────────

export const mockRoomTypes: Record<string, RoomType[]> = {
  h1: [
    {
      id: "rm-h1-deluxe",
      hotel_id: "h1",
      name: "Deluxe King Room",
      description: "45 m² of contemporary comfort with Gulf or city views.",
      price_per_night: 850,
      capacity: 2,
      beds: "1 King",
      amenities: ["Free Wi-Fi", "City View", "Nespresso Machine", "Smart TV"],
      is_available: true,
      created_at: "2026-01-05T00:00:00",
    },
    {
      id: "rm-h1-exec",
      hotel_id: "h1",
      name: "Executive Gulf Suite",
      description: "Separate living area, lounge access, and panoramic sea views.",
      price_per_night: 1650,
      capacity: 3,
      beds: "1 King + Sofa",
      amenities: [
        "Free Wi-Fi",
        "Sea View",
        "Executive Lounge Access",
        "Butler Service",
        "Bathtub",
      ],
      is_available: true,
      created_at: "2026-01-05T00:00:00",
    },
    {
      id: "rm-h1-royal",
      hotel_id: "h1",
      name: "Royal Suite",
      description: "Our flagship suite — 180 m² of unrivalled luxury.",
      price_per_night: 4200,
      capacity: 4,
      beds: "2 King",
      amenities: [
        "Free Wi-Fi",
        "Panoramic Sea View",
        "Private Dining",
        "Dedicated Butler",
        "Spa Bath",
        "Airport Limousine",
      ],
      is_available: true,
      created_at: "2026-01-05T00:00:00",
    },
  ],
  h2: [
    {
      id: "rm-h2-superior",
      hotel_id: "h2",
      name: "Superior Room",
      description: "Elegant room with St. Regis butler service included.",
      price_per_night: 780,
      capacity: 2,
      beds: "1 King",
      amenities: ["Free Wi-Fi", "Butler Service", "Garden View", "Smart TV"],
      is_available: true,
      created_at: "2026-01-08T00:00:00",
    },
    {
      id: "rm-h2-grand",
      hotel_id: "h2",
      name: "Grand Deluxe Sea View",
      description: "Beachfront views and a spacious marble bathroom.",
      price_per_night: 1450,
      capacity: 3,
      beds: "1 King + Sofa",
      amenities: [
        "Free Wi-Fi",
        "Sea View",
        "Butler Service",
        "Beach Access",
        "Bathtub",
      ],
      is_available: true,
      created_at: "2026-01-08T00:00:00",
    },
  ],
  h3: [
    {
      id: "rm-h3-mondrian",
      hotel_id: "h3",
      name: "Mondrian King",
      description: "Statement design with bold interiors and city views.",
      price_per_night: 720,
      capacity: 2,
      beds: "1 King",
      amenities: ["Free Wi-Fi", "City View", "Designer Interiors", "Smart TV"],
      is_available: true,
      created_at: "2026-01-12T00:00:00",
    },
    {
      id: "rm-h3-loft",
      hotel_id: "h3",
      name: "Skyline Loft Suite",
      description: "Double-height loft suite with rooftop pool access.",
      price_per_night: 1900,
      capacity: 3,
      beds: "1 King + Sofa",
      amenities: [
        "Free Wi-Fi",
        "Skyline View",
        "Rooftop Pool Access",
        "Bar Cart",
        "Bathtub",
      ],
      is_available: true,
      created_at: "2026-01-12T00:00:00",
    },
  ],
  h4: [
    {
      id: "rm-h4-studio",
      hotel_id: "h4",
      name: "Marina Studio Suite",
      description: "Self-contained studio with kitchenette and marina views.",
      price_per_night: 420,
      capacity: 2,
      beds: "1 Queen",
      amenities: ["Free Wi-Fi", "Kitchenette", "Marina View", "Free Parking"],
      is_available: true,
      created_at: "2026-01-18T00:00:00",
    },
    {
      id: "rm-h4-two-bed",
      hotel_id: "h4",
      name: "Two-Bedroom Residence",
      description: "Ideal for families — full kitchen and living room.",
      price_per_night: 950,
      capacity: 5,
      beds: "1 King + 2 Twin",
      amenities: [
        "Free Wi-Fi",
        "Full Kitchen",
        "Marina View",
        "Washer/Dryer",
        "Free Parking",
      ],
      is_available: true,
      created_at: "2026-01-18T00:00:00",
    },
  ],
  h5: [
    {
      id: "rm-h5-classic",
      hotel_id: "h5",
      name: "Classic Room",
      description: "Refined comfort in the heart of Abuja's CBD.",
      price_per_night: 310,
      capacity: 2,
      beds: "1 King",
      amenities: ["Free Wi-Fi", "City View", "Work Desk", "Smart TV"],
      is_available: true,
      created_at: "2026-01-22T00:00:00",
    },
    {
      id: "rm-h5-exec",
      hotel_id: "h5",
      name: "Executive Suite",
      description: "Separate lounge, rooftop access, and premium amenities.",
      price_per_night: 680,
      capacity: 3,
      beds: "1 King + Sofa",
      amenities: [
        "Free Wi-Fi",
        "Rooftop Lounge Access",
        "Work Desk",
        "Bathtub",
        "Airport Transfer",
      ],
      is_available: true,
      created_at: "2026-01-22T00:00:00",
    },
  ],
  h6: [
    {
      id: "rm-h6-garden",
      hotel_id: "h6",
      name: "Garden Villa",
      description: "Private garden villa with a tranquil terrace.",
      price_per_night: 540,
      capacity: 2,
      beds: "1 King",
      amenities: ["Free Wi-Fi", "Private Terrace", "Garden View", "Free Parking"],
      is_available: true,
      created_at: "2026-02-02T00:00:00",
    },
  ],
};

// ─── Mock Hotel Booking Requests ─────────────────────────────────────────────

export const mockHotelBookings: HotelBooking[] = [
  {
    id: "bkg-001",
    hotel_id: "h1",
    room_type_id: "rm-h1-exec",
    guest_name: "Khalid Al-Mansoori",
    guest_email: "khalid@example.com",
    guest_phone: "+974 5500 1122",
    check_in: "2026-04-17",
    check_out: "2026-04-19",
    nights: 2,
    rooms: 1,
    guests: 2,
    special_requests: "High floor with sea view if possible. Late check-out.",
    estimated_total: 3300,
    status: "pending",
    created_at: "2026-03-20T09:15:00",
  },
  {
    id: "bkg-002",
    hotel_id: "h2",
    room_type_id: "rm-h2-grand",
    guest_name: "Aisha Al-Thani",
    guest_email: "aisha@example.com",
    guest_phone: "+974 5511 3344",
    check_in: "2026-05-01",
    check_out: "2026-05-04",
    nights: 3,
    rooms: 2,
    guests: 4,
    special_requests: "Two connecting rooms for our family.",
    estimated_total: 8700,
    status: "confirmed",
    created_at: "2026-03-21T14:40:00",
  },
  {
    id: "bkg-003",
    hotel_id: "h5",
    room_type_id: "rm-h5-exec",
    guest_name: "Omar Hassan",
    guest_email: "omar@example.com",
    guest_phone: "+234 805 123 4567",
    check_in: "2026-06-09",
    check_out: "2026-06-12",
    nights: 3,
    rooms: 1,
    guests: 1,
    estimated_total: 2040,
    status: "pending",
    created_at: "2026-03-23T11:05:00",
  },
  {
    id: "bkg-004",
    hotel_id: "h4",
    room_type_id: "rm-h4-two-bed",
    guest_name: "Fatima Al-Kuwari",
    guest_email: "fatima@example.com",
    guest_phone: "+974 5522 7788",
    check_in: "2026-05-02",
    check_out: "2026-05-03",
    nights: 1,
    rooms: 1,
    guests: 4,
    special_requests: "Cot for an infant, please.",
    estimated_total: 950,
    status: "cancelled",
    created_at: "2026-03-24T16:20:00",
  },
];
